### ISSUE TITLE
Consulta 

### ISSUE THREAD

**Issue by gatomo-oficial** [LHCLYT/CactusFireDocs#1]
### Hola, querría preguntar unas cuantas cosas relacionadas con el bot

- ¿Dónde puedo conseguir todos los NPM de los que hace uso CactusFire?
- ¿Hay planeado alguna nueva estrategia de promoción abusiva además de enviar MD o poner botones con un invite en todas las funciones del bot?
- Si el bot no copia y pega funciones de terceros, ¿por qué he sido baneado? Si lo que hubiera dicho fuera mentira, no habría ninguna justificación para banear por ese motivo

Muchas gracias

**Comment by AxelGhoulX** [comment]
Hola, querría preguntar una cosita
¿Dónde puedo conseguir los códigos de está mierda?
Las necesito para mi bot y sustituir este gran cagarro de bot. Un Saludo.
PD: Kamerr aprende a escribir en tú propio idioma.

**Comment by LHCLYT** [comment]
> Hola, querría preguntar una cosita ¿Dónde puedo conseguir los códigos de está mierda? Las necesito para mi bot y sustituir este gran cagarro de bot. Un Saludo. PD: Kamerr aprende a escribir en tú propio idioma.

¡Claro Axel! Es muy sencillo, recuerda que CactusFire, es OpenSource, y puedes acceder desde [aquí](https://bit.ly/cactussource)
